apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-binding
  namespace: default
subjects:
  - kind: User
    name: fernando
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: demo-permissions
  apiGroup: rbac.authorization.k8s.io


