apiVersion: v1
kind: PersistenceVolumeClaim
metadata:
  name: pvc-viernes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: viernes-storageclass