apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-permissions
  namespace: default
rules:
  - apiGroups: [""] # coreApi representado "" | apps | batch | extensions | policy | 
    resources: ["pods", "services", "configmap"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemomsets"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
