apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role-permission
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: default
subjects:
  - kind: User
    name: developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role-permission
  apiGroup: rbac.authorization.k8s.io

