apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: port-forward-role
  namespace: permission-manager
rules:
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-forward-binding
  namespace: permission-manager
subjects:
  - kind: User
    name: minikube
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: port-forward-role
  apiGroup: rbac.authorization.k8s.io

