apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-failed
spec:
  schedule: "* * * * *" #se ejecuta cada minuto
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: cronjob-failed-container
              image: busybox
              command: ["sh", "-c", "exit 1"]
          restartPolicy: OnFailure