apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-success
spec:
  schedule: "* * * * *" #se ejecuta cada minuto
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-date-container
              image: busybox
              command: ["date"]
          restartPolicy: Never