apiVersion: batch/v1
kind: Job
metadata:
  name: job-failed
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: job-failed-container
          image: busybox
          command: ["sh", "-c", "exit 1"]
      restartPolicy: Never
