apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-prometheus-deployment
spec:
  selector:
    matchLabels:
      app: node-prometheus
  template:
    metadata:
      labels:
        app: node-prometheus
    spec:
      containers:
      - name: node-prometheus-container
        image: fercdevv/node-prometheus:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: node-prometheus
spec:
  type: ClusterIP
  selector:
    app: node-prometheus
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080