apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-deployment
spec:
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress-container
        image: fercdevv/cpu-stress:v2
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "20m"
        ports:
        - containerPort: 80
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cpu-stress-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-stress-deployment
  updatePolicy:
    updateMode: "Auto" # puede ser "Auto", "Off", "Initial"