apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dp-ext
  template:
    metadata:
      labels:
        app: nginx-dp-ext
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 80
  strategy:
    type: Recreate
