apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp-ext
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-dp-ext
  template:
    metadata:
      labels:
        app: nginx-dp-ext
    spec:
      containers:
      - name: nginx-container-ext
        image: nginx
        ports:
        - containerPort: 80
  strategy:
    type: Recreate
