apiVersion: v1
kind: Secret
metadata:
  name: permission-manager
  namespace: permission-manager
type: Opaque
stringData:
  PORT: '4000'
  CLUSTER_NAME: minikube
  CONTROL_PLANE_ADDRESS: "https://127.0.0.1:58176"
  BASIC_AUTH_PASSWORD: "codigo"