apiVersion: v1
kind: PersistentVolume
metadata:
  name: poyecto-pv
  namespace: proyecto-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/demo-logs"
