apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sg-lunes
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sg-lunes
  hostPath:
    path: /tmp/data2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sg-lunes
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-local
spec:
  containers:
    - name: pod-local-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: local-volume
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: pvc-local