apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vpa-deployment
spec:
  selector:
    matchLabels:
      app: app-nginx-vpa
  template:
    metadata:
      labels:
        app: app-nginx-vpa
    spec:
      containers:
      - name: app-nginx-vpa-container
        image: nginx:alpine
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "20m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-vpa-service
spec:
  selector:
    app: app-nginx-vpa
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer