apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sample-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-vpa-deployment
  updatePolicy:
    updateMode: "Auto" # puede ser "Auto", "Off", "Initial"