apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-autoscalling-deployment
spec:
  selector:
    matchLabels:
      app: app-nginx-auto
  template:
    metadata:
      labels:
        app: app-nginx-auto
    spec:
      containers:
      - name: app-nginx-auto-container
        image: nginx:alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-auto-service
spec:
  selector:
    app: app-nginx-auto
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer