apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-2
spec:
  containers:
    - name: pod-secret-2-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password