apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: pod-secret-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: custom-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: custom-secret
              key: password