apiVersion: v1
kind: Pod
metadata:
  name: app-pod-vl
  labels:
    name: myapp
spec:
  containers:
  - name: app-container
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: app-config-vl
    
